"""empty message

Revision ID: 378099587bca
Revises: a289d31f705d
Create Date: 2023-07-30 19:26:02.081867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378099587bca'
down_revision = 'a289d31f705d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_phoneNumber', table_name='users')
    op.create_index(op.f('ix_users_phoneNumber'), 'users', ['phoneNumber'], unique=False)
    op.drop_index('ix_users_profilePictureUrl', table_name='users')
    op.create_index(op.f('ix_users_profilePictureUrl'), 'users', ['profilePictureUrl'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_profilePictureUrl'), table_name='users')
    op.create_index('ix_users_profilePictureUrl', 'users', ['profilePictureUrl'], unique=False)
    op.drop_index(op.f('ix_users_phoneNumber'), table_name='users')
    op.create_index('ix_users_phoneNumber', 'users', ['phoneNumber'], unique=False)
    # ### end Alembic commands ###
